version: "3.8"

services:
  database_sample:
    image: postgres
    container_name: database_sample
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=sample
      - POSTGRES_DB=prisma_sample
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: prisma_sample
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_sample
    depends_on:
      - database_sample

volumes:
  pgdata:
    driver: local